broadcast:
  title: '&4&lBROADCAST &7» '
  messages:
    one: '&aConfigure this message in config.yml, powered by skky (skky#9999).'
    two: '&aConfigure this message in config.yml, powered by skky (skky#9999).'
    three: '&aConfigure this message in config.yml, powered by skky (skky#9999).'
    four: '&aConfigure this message in config.yml, powered by skky (skky#9999).'
    five: '&aConfigure this message in config.yml, powered by skky (skky#9999).'